version: "3.9"

services:
  flask:
    build: ./dashboard-llm
    container_name: flask_app
    restart: always
    expose:
      - "5000"
  
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/websocket.conf:/etc/nginx/conf.d/
    depends_on:
      - flask
